src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Role\Role;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * @ORM\Entity
 * @UniqueEntity(fields="email", message="Email already taken")
 * @UniqueEntity(fields="username", message="Username already taken")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 */
class User implements AdvancedUserInterface, \Serializable
{

    const ROLE_SUPER_ADMIN = 'Administrador';
    const ROLE_ADMIN = 'Gerencial';
    const ROLE_USER = 'Usuario';

    static public $arrRoles = array(
        'ROLE_USER' => self::ROLE_USER,
        'ROLE_ADMIN' => self::ROLE_ADMIN,
        'ROLE_SUPER_ADMIN' => self::ROLE_SUPER_ADMIN
    );

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    /**
     * The below length depends on the "algorithm" you use for encoding
     * the password, but this works well with bcrypt.
     *
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="company_name", type="string", length=150, nullable=true)
     */
    private $companyName;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=150, nullable=true)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=150, nullable=true)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=150, nullable=true)
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=50, nullable=true)
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="state", type="string", length=50, nullable=true)
     */
    private $state;

    /**
     * @var string
     *
     * @ORM\Column(name="zip", type="string", length=20, nullable=true)
     */
    private $zip;

    /**
     * @var string
     *
     * @ORM\Column(name="phone", type="string", length=30, nullable=true)
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(name="contact_preference", type="string", length=20, nullable=true)
     */
    private $contactPreference;

    /**
     * @var string $role
     *
     * @ORM\Column(name = "role", type = "string", length = 40)
     */
    private $role;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(name="deleted", type="boolean")
     */
    private $deleted = false;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @Assert\File(
     *      maxSize="5242880",
     *      mimeTypes = {
     *          "image/png",
     *          "image/jpeg",
     *          "image/jpg",
     *      },
     *      mimeTypesMessage="Please, upload your photo as a image file."
     * )
     */
    private $photo;

    public function __construct()
    {
//        $this->isActive = true;
        // may not be needed, see section on salt below
        // $this->salt = md5(uniqid('', true));
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getCompanyName()
    {
        return $this->companyName;
    }

    public function getCompany()
    {
        if ( ! $this->companyName ) {
            return 'Individual';
        }

        return $this->companyName;
    }

    /**
     * @param string $companyName
     */
    public function setCompanyName($companyName)
    {
        $this->companyName = $companyName;
    }

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param string $lastName
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
    }

    public function getFullName()
    {
    	return $this->firstName . ' '. $this->lastName;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param string $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param string $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param string $phone
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
    }

    /**
     * @return string
     */
    public function getContactPreference()
    {
        return $this->contactPreference;
    }

    /**
     * @param string $contactPreference
     */
    public function setContactPreference($contactPreference)
    {
        $this->contactPreference = $contactPreference;
    }

    /**
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * @param string $state
     */
    public function setState($state)
    {
        $this->state = $state;
    }

    /**
     * @return string
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * @param string $zip
     */
    public function setZip($zip)
    {
        $this->zip = $zip;
    }

    // other properties and methods



    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        if (!is_null($password)) {
            $this->plainPassword = $password;
        }

        return $this;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getSalt()
    {
        // The bcrypt algorithm doesn't require a separate salt.
        // You *may* need a real salt if you choose a different encoder.
        return null;
    }

    // other methods, including security methods like getRoles()

    /**
     * Set role
     *
     * @param $role
     * @return User
     */
    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return Role[] The user roles
     */
    public function getRoles()
    {
        return array($this->role);
    }

    public function roleName()
    {
        return self::$arrRoles[$this->role];
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }

    public function disabled()
    {
    	$this->isActive = false;

    	return $this;
    }

		public function enabled()
		{
			$this->isActive = true;

			return $this;
		}

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }

    /**
     * @return mixed
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * @param mixed $photo
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;
    }

    /**
     * @return bool
     */
    public function isDeleted()
    {
        return $this->deleted;
    }

    /**
     * @param bool $deleted
     */

src/AppBundle/Entity/UserBankInformation.php
<?php

namespace AppBundle\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * UserBankInformation
 *
 * @ORM\Table(name="user_bank_information")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserBankInformationRepository")
 */
class UserBankInformation
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var User $user
     *
     * @ORM\ManyToOne(targetEntity = "AppBundle\Entity\User")
     * @ORM\JoinColumn(nullable = false)
     */
    private $user;

    /**
     * @var string
     *
     * @ORM\Column(name="type_method", type="string", length=50, nullable=false)
     */
    private $typeMethod;

    /**
     * @var string
     *
     * @ORM\Column(name="information_one", type="string", length=150, nullable=false)
     */
    private $information_one;

		/**
		 * @var string
		 *
		 * @ORM\Column(name="information_two", type="string", length=150, nullable=true)
		 */
		private $information_two;

		/**
		 * @var string
		 *
		 * @ORM\Column(name="information_three", type="string", length=150, nullable=true)
		 */
		private $information_three;

		/**
		 * @var DateTime
		 *
		 * @ORM\Column(name="created_at", type="datetime", nullable=true)
		 */
		private $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return User
	 */
	public function getUser()
	{
		return $this->user;
	}

	/**
	 * @param User $user
	 */
	public function setUser($user)
	{
		$this->user = $user;
	}

	/**
	 * @return string
	 */
	public function getTypeMethod()
	{
		return $this->typeMethod;
	}

	/**
	 * @param string $typeMethod
	 */
	public function setTypeMethod($typeMethod)
	{
		$this->typeMethod = $typeMethod;
	}

	/**
	 * @return string
	 */
	public function getInformationOne()
	{
		return $this->information_one;
	}

	/**
	 * @param string $information_one
	 */
	public function setInformationOne($information_one)
	{
		$this->information_one = $information_one;
	}

	/**
	 * @return string
	 */
	public function getInformationTwo()
	{
		return $this->information_two;
	}

	/**
	 * @param string $information_two
	 */
	public function setInformationTwo($information_two)
	{
		$this->information_two = $information_two;
	}

	/**
	 * @return DateTime
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

	/**
	 * @param DateTime $createdAt
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;
	}

	/**
	 * @return string
	 */
	public function getInformationThree()
	{
		return $this->information_three;
	}

	/**
	 * @param string $information_three
	 */
	public function setInformationThree($information_three)
	{
		$this->information_three = $information_three;
	}
}

src/AppBundle/Form/UserType.php
<?php
namespace AppBundle\Form;

use AppBundle\Entity\User;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('companyName', TextType::class, [
                'required' => false,
                'attr' => ['class' => 'form-control', 'placeholder' => 'Company name']
            ])
            ->add('email', EmailType::class, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Email']
            ])
            ->add('firstName', TextType::class, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'First name']
            ])
            ->add('lastName', TextType::class, [
                'attr' => ['class' => 'form-control', 'placeholder' => 'Last name']
            ])
            ->add('plainPassword', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options'  => array('label' => 'Password', 'attr' => ['class' => 'form-control', 'placeholder' => 'Password']),
                'second_options' => array('label' => 'Repeat Password', 'attr' => ['class' => 'form-control', 'placeholder' => 'Confirm password'],),
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'data_class' => User::class,
        ));
    }
}

src/AppBundle/Resources/views/admin/user/_form_bank.html.twig
{% set fieldAccount = 'hidden' %}
{% if bankInformation is defined %}
    {% if bankInformation.typeMethod == 'deposit' %}
        {% set fieldAccount = '' %}
    {% endif %}
{% endif %}
<form class="needs-validation" novalidate method="post" action="{{ path('admin_user_update_information_bank') }}" enctype="multipart/form-data">
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="validationServer013">Payment Method</label>
            {{ form_widget(formBankInformation.typeMethod) }}
            <div class="invalid-feedback">
                You first name is mandatory
            </div>
        </div>
        <div class="col-md-4 mb-3">
            <label id="info_one">Confirm address to send check</label>
            {{ form_widget(formBankInformation.informationOne) }}
            <div class="invalid-feedback">
                This field is mandatory
            </div>
        </div>
        <div class="col-md-4 mb-3 {{ fieldAccount }}" id="field-account-number">
            <label id="info_two">Account Number</label>
            {{ form_widget(formBankInformation.informationTwo) }}
            <div class="invalid-feedback">
                This field is mandatory
            </div>
        </div>
        <div class="col-md-4 mb-3"></div>
        <div class="col-md-8 mb-3 {{ fieldAccount }}" id="field-account-bank-name">
            <label id="info_three">Bank Name</label>
            {{ form_widget(formBankInformation.informationThree) }}
            <div class="invalid-feedback">
                This field is mandatory
            </div>
        </div>
    </div>
    <input type="hidden" name="id" value="{{ user.id }}">
    <button class="btn btn-primary btn-lg" name="save-info-bank" type="submit">Save Bank Information</button>
</form>

src/AppBundle/Resources/views/admin/user/list.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include('@App/global/_header_logged.html.twig') }}
{% endblock %}
{% block top_content %}{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row flex-xl-nowrap">

        {{ include('@App/global/_menu.html.twig') }}

        <main class="col-12 col-md-9 col-xl-10 py-md-3 pl-md-5 ct-content" role="main">
            <div class="ct-page-title">
                <h1 class="ct-title" id="content">Users</h1>
                <div class="avatar-group mt-3">
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-2">
                    <a href="{{ path('admin_user_list', { 'export' : true }) }}" class="btn btn-sm btn-info"><i class="fa fa-file-excel-o"></i> Export</a>
                </div>
                <div class="col-md-6">
                    <input class="form-control-sm" style="width: 80%" id="search-user" type="text" placeholder="Search">
                </div>
            </div>

            <table id="referrals" class="table table-hover table-sm" >
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Full name</th>
                    <th>Company</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                    {% for item in list  %}
                        <tr class="row-{{ item.id }}">
                            <td><a href="{{ path('admin_user_view', { 'id': item.id }) }}">{{ item.id }}</a></td>
                            <td><a href="{{ path('admin_user_view', { 'id': item.id }) }}">{{ item.fullName }}</a></td>
                            <td>{{ item.company }}</td>
                            <td>{{ item.email }}</td>
                            <td>
                                {% if item.isEnabled %}
                                    <i class="ni ni-check-bold text-success"></i>
                                {% else %}
                                    <i class="ni ni-button-pause text-danger"></i>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{{ path('admin_user_view', { 'id': item.id }) }}"><i class="fa fa-edit"></i></a>
                                <a href="javascript:void(0)" href="#" data-path="{{ path('admin_user_delete', { 'id': item.id }) }}" data-id="{{ item.id }}" class="remove-list text-danger"><i class="fa fa-remove"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </div>
    {% endblock %}

    {% block javascripts %}
        {{ parent() }}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

        <script>
            $(document).ready(function(){
                $("#search-user").on("keyup", function() {
                    let value = $(this).val().toLowerCase();

                    $("#referrals tr").filter(function() {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                    });
                });

                $('.remove-list').on('click', function () {
                    var id = $( this ).data('id');
                    var path = $( this ).data('path');

                    $.confirm({
                        theme: 'modern',
                        closeIcon: true,
                        animation: 'scale',
                        type: 'blue',
                        title: 'Delete',
                        content: 'Confirm that you want to delete the user?',
                        buttons: {
                            confirm: {
                                text: 'Sí, Eliminar',
                                btnClass: 'btn-red',
                                action: function(){
                                    $.get(
                                        path,
                                        function(data, status) {
                                            var result = data;
                                            console.log(result);

                                            if (result.code === 400) {
                                                $.alert({
                                                    type: 'red',
                                                    typeAnimated: true,
                                                    title: 'Cannot be deleted',
                                                    content: '<h6>' + result.error + '</h6>'
                                                });
                                            } else {
                                                $('.row-' + id).remove();
                                            }
                                        }
                                    );
                                }
                            },
                            cancel: {
                                text: 'Cancel'
                            }
                        }
                    });
                });
            });
        </script>
    {% endblock %}

    {% block stylesheets %}
        {{ parent() }}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
        <link type="text/css" href="{{ asset('assets/css/docs.min.css') }}" rel="stylesheet">

        <style>
            main {
                overflow: initial;
            }
        </style>
    {% endblock %}

src/AppBundle/Resources/views/admin/user/view.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ include('@App/global/_header_logged.html.twig') }}
{% endblock %}
{% block top_content %}{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row flex-xl-nowrap">

        {{ include('@App/global/_menu.html.twig') }}

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 ct-content" role="main">
            {{ include('_flash_messages.html.twig') }}

            <div class="ct-page-title">
                <a href="{{ path('admin_user_list') }}" class="btn btn-info btn-sm pull-right">Back to list</a>
                <h1 class="ct-title" id="content">Profile Information</h1>

                <div class="avatar-group mt-3">
                </div>
            </div>

            <form action="{{ path('admin_user_update') }}" method="post">

                {{ include('@App/admin/user/_form.html.twig') }}

                <input type="hidden" name="id" value="{{ user.id }}">
                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
            </form>

            <div class="ct-page-title" style="margin-top: 40px;">
                <h1 class="ct-title" id="content">Earnings</h1>
                <div class="avatar-group mt-3">
                </div>
            </div>

            <i class="ni ni-bold-right"></i>
            Current Month Earnings* ({{ "now"|date('m')|month }}): $ {{ earned.month|number_format(2, '.', ',') }}<br>
            <i class="ni ni-bold-right"></i>
            Previous Month Earnings* ({{ previousMonth|month }}): $ {{ earned.previousMonth|number_format(2, '.', ',') }} <br>
            <i class="ni ni-bold-right"></i> Total Earnings Year to Date: ${{ earned.earnedYear|number_format(2, '.', ',') }}<br>

            <div class="ct-page-title">
                <h1 class="ct-title" id="content">Referral Snapshot</h1>
                <div class="avatar-group mt-3">
                </div>
            </div>

            <i class="ni ni-bold-right"></i> Submitted: {{ status.submitted }}<br>
            <i class="ni ni-bold-right"></i> Closed Won: {{ status.closed }}<br>
            <i class="ni ni-bold-right"></i> Paid: {{ status.paid }}<br>

            <div class="ct-page-title" style="margin-top: 50px;">
                <h1 class="ct-title" id="content">Bank Account Information</h1>
                <div class="avatar-group mt-3">
                </div>
            </div>


                {{ include('@App/admin/user/_form_bank.html.twig') }}


                {% if bankInformation %}
{#                    <div class="col-md-4">#}
{#                        <div class="form-group">#}
{#                            <label>Payment Method</label>#}
{#                            <div class="form-control">#}
{#                                {{ bankInformation.typeMethod|payment_method }}#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    {% set titleOne = 'Address to send check' %}#}
{#                    {% set col = '6' %}#}
{#                    {% if bankInformation.typeMethod == 'check' %}#}
{#                        {% set titleOne = 'Routing Number' %}#}
{#                        {% set col = '4' %}#}
{#                    {% endif %}#}
{#                    <div class="col-md-{{ col }}">#}
{#                        <label>{{ titleOne }}</label>#}
{#                        <div class="form-control">#}
{#                            {{ bankInformation.informationOne }}#}
{#                        </div>#}
{#                    </div>#}

{#                    {% if bankInformation.typeMethod == 'deposit' %}#}
{#                        <div class="col-md-4">#}
{#                            <label>Account Number</label>#}
{#                            <div class="form-control">#}
{#                                {{ bankInformation.informationTwo }}#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="col-md-4">#}
{#                            <label>Bank Name</label>#}
{#                            <div class="form-control">#}
{#                                {{ bankInformation.informationThree }}#}
{#                            </div>#}
{#                        </div>#}
{#                    {% endif %}#}
                {% else %}
                    <h6 class="text-danger ml-4">The user has not updated their bank information</h6>
                {% endif %}

        </main>
    </div>
    {% endblock %}

    {% block javascripts %}
        {{ parent() }}

        <script type="application/javascript">
            (function() {
                'use strict';
                $('#app_user_bank_information_typeMethod').change( function () {
                    let value = $(this).val();
                    if ( value === 'deposit' ) {
                        $('#field-account-number').removeClass('hidden');
                        $('#field-account-bank-name').removeClass('hidden');
                        $('#info_one').text('Routing number');
                    } else {
                        $('#field-account-number').addClass('hidden');
                        $('#field-account-bank-name').addClass('hidden');
                        $('#info_one').text('Confirm address to send check');
                    }
                })
            })();
        </script>

        <script>
            $(function() {
                $('#is-active').change(function() {
                    let message ;
                    if ( $(this).prop('checked') === true ) {
                        //change status user
                        message = 'User is enabled';
                    } else {
                        message = 'User is disabled';
                    }

                    $.ajax({
                        url: "{{ path('admin_user_change_status', { 'id': user.id }) }}",
                        method: "GET",
                        beforeSend: function() {

                        }
                    })
                    .done(function( data ) {
                        $('#console-event').html(message);
                    });
                })
            })
        </script>
    {% endblock %}

    {% block stylesheets %}
        {{ parent() }}
        <link type="text/css" href="{{ asset('assets/css/docs.min.css') }}" rel="stylesheet">

        <style>
            main {
                overflow: initial;
            }

            input:checked + .slider {
                background-color: #66bb6a;
            }

            .switch {
                position: relative;
                display: inline-block;
                width: 60px;
                height: 34px;
            }

            .switch input {
                opacity: 0;
                width: 0;
                height: 0;
            }

            .slider {
                position: absolute;
                cursor: pointer;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background-color: #ccc;
                -webkit-transition: .4s;
                transition: .4s;
            }

            .slider:before {
                position: absolute;
                content: "";
                height: 26px;
                width: 26px;
                left: 4px;
                bottom: 4px;
                background-color: white;
                -webkit-transition: .4s;
                transition: .4s;
            }

            input:checked + .slider {
                background-color: #2dce89;
            }

            input:focus + .slider {
                box-shadow: 0 0 1px #2dce89;
            }

            input:checked + .slider:before {
                -webkit-transform: translateX(26px);
                -ms-transform: translateX(26px);
                transform: translateX(26px);
            }

            /* Rounded sliders */
            .slider.round {
                border-radius: 34px;
            }

            .slider.round:before {
                border-radius: 50%;
            }
        </style>
    {% endblock %}